@Host=http://localhost:5289

POST {{Host}}/auth/login
Content-Type: application/json

{
    "email": "vedad.h96@sda.com",
    "password": "vedator"
}

###
POST {{Host}}/auth/register
Content-Type: application/json

{
    "firstName": "Vedad",
    "lastName": "Herceglija",
    "email": "vedad.h96@sda.com",
    "password": "vedator"
}

###
